server:
  port: 8888
 
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: gateway-service-PRO290
  cloud:
    gateway:
      routes:
      - id: account
        uri: lb://ACCOUNT-SERVICE
        predicates:
        - Path=/account/**

      - id: card #whatever
        uri: lb://CARD-SERVICE #Eureka Service
        predicates:
        - Path=/card/**      #pathing
        #you can now hit this api gateway via: http://localhost:8888/api1/abc

      - id: rules
        uri: lb://RULES-SERVICE
        predicates:
        - Path=/rules/**
        #you can now hit endpoint like: http://localhost:8888/test1 this somehow maps to the minimal api endpoints

      - id: webscraper
        uri: lb://WEBSCRAPER
        predicates:
          - Path=/webscraper/**

      - id: email
        uri: lb://EMAIL-SERVICE
        predicates:
        - Path=/email/**
        #you can now hit http://localhost:8888/api2